In [3]:
import torch
#1d tensor
x = torch.tensor([1,2,3])

#2d tensor

y = torch.tensor([[1,2,3], [4,5,6]])
print(x)
print(y)

tensor([1, 2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [15]:
a = torch.rand(3,3)
b = torch.zeros(3,3)
c = torch.ones(2,3)

print(a)
print(b)
print(c,"\n")

print("printing the shapes of each tensor\n")

print(a.shape)
print(b.shape)
print(c.shape)

tensor([[0.3698, 0.9811, 0.6622],
        [0.7806, 0.5349, 0.8493],
        [0.2766, 0.9298, 0.0472]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

printing the shapes of each tensor

torch.Size([3, 3])
torch.Size([3, 3])
torch.Size([2, 3])


In [17]:
print(a+b)
print(a*b)

tensor([[0.3698, 0.9811, 0.6622],
        [0.7806, 0.5349, 0.8493],
        [0.2766, 0.9298, 0.0472]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [3]:
#3d tensors
# 👉 Meaning:

# 2 matrices
# each has 2 rows
# each row has 2 columns

# Think:

# (depth, rows, columns)
import torch
x = torch.tensor([
    [[1,2],[3,4]],
     [[23,34],[25,27]]
    ])

print(x)
print(x.shape)


# 🎯 REAL LIFE USE (IMPORTANT)

# 3D tensors are used in:

# 📸 Images (very important for you)
# 3D = (channels, height, width)

# Example:

# RGB image → 3 channels
# 👉 shape = (3, H, W)

tensor([[[ 1,  2],
         [ 3,  4]],

        [[23, 34],
         [25, 27]]])
torch.Size([2, 2, 2])


In [4]:
x = torch.rand(3,2,2)
print(x)
print(x.shape)

tensor([[[0.8641, 0.1055],
         [0.8336, 0.9052]],

        [[0.7206, 0.1667],
         [0.4785, 0.2024]],

        [[0.5818, 0.3386],
         [0.8267, 0.7476]]])
torch.Size([3, 2, 2])
